# Generated by Django 4.2.3 on 2023-08-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ready_to_be_active',
            new_name='is_couch_potato',
        ),
    ]
