# Generated by Django 4.2.3 on 2023-08-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_0005_alter_profile_age_0005_matcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activities_today',
            field=models.CharField(choices=[('RU', 'Running'), ('WL', 'Weight Lifting'), ('GC', 'Group Classes'), ('BR', 'Bike Riding'), ('TE', 'Tennis'), ('SQ', 'Squash'), ('WA', 'Walking'), ('BA', 'Badminton'), ('SW', 'Swimming'), ('WA', 'Walking'), ('HI', 'Hiking'), ('P', 'Pilates'), ('SU', 'Surfing'), ('SK', 'Skateboarding')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.CharField(max_length=200),
        ),
    ]
