# Generated by Django 4.2.3 on 2023-08-07 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_0005_alter_profile_age_0005_matcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matcher',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matcher',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
