# Generated by Django 4.2.3 on 2023-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_profile_activities_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
