# Generated by Django 4.2.3 on 2023-08-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment'),
        ('main_app', '0010_remove_profile_short_bio'),
    ]

    operations = [
    ]
