# Generated by Django 4.2.3 on 2023-08-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile_created_at_profile_latitude_and_more'),
        ('main_app', '0011_merge_0007_comment_0010_remove_profile_short_bio'),
    ]

    operations = [
    ]
