# Generated by Django 4.2.3 on 2023-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_profile_chosen_activities_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matcher',
            name='chosen_activities',
            field=models.CharField(choices=[('RU', 'Running'), ('WL', 'Weight Lifting'), ('GC', 'Group Classes'), ('BR', 'Bike Riding'), ('TE', 'Tennis'), ('SQ', 'Squash'), ('WA', 'Walking'), ('BA', 'Badminton'), ('SW', 'Swimming'), ('WA', 'Walking'), ('HI', 'Hiking'), ('P', 'Pilates'), ('SU', 'Surfing'), ('SK', 'Skateboarding')], default='RU', max_length=2),
        ),
        migrations.AlterField(
            model_name='matcher',
            name='latitude',
            field=models.FloatField(blank=True, default='0.0000000', null=True),
        ),
        migrations.AlterField(
            model_name='matcher',
            name='longitude',
            field=models.FloatField(blank=True, default='0.0000000', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default='0.0000000', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default='0.0000000', null=True),
        ),
    ]
