# Generated by Django 4.2.3 on 2023-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_matcher_latitude_alter_matcher_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=10.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=10.0),
        ),
        migrations.DeleteModel(
            name='Matcher',
        ),
    ]
