# Generated by Django 4.2.3 on 2023-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_profile_latitude_alter_profile_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=51.515425825794125),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=-0.07266577316737018),
        ),
    ]
