# Generated by Django 4.2.3 on 2023-08-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20230808_1257'),
        ('main_app', '0012_merge_20230808_1259'),
        ('main_app', '0018_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
    ]
