# Generated by Django 4.2.3 on 2023-08-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_merge_20230808_1735'),
        ('main_app', '0020_photo'),
    ]

    operations = [
    ]
