# Generated by Django 4.2.3 on 2023-08-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0025_alter_profile_chosen_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='target_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
